### ISSUE TITLE
Text falls off when rendered

### ISSUE THREAD

**Issue by WeeJeWel** [jihchi/mermaid.ink#1]
![demo](https://user-images.githubusercontent.com/319873/71619532-14753a00-2bc5-11ea-97da-c8650c03f2dc.jpeg)

As you can see, the text is overflowing when rendered to a JPEG.

**Comment by jihchi** [comment]
Thanks for the feedback @WeeJeWel , I'll take a look.

**Comment by jihchi** [comment]
According to this [comment](https://github.com/mermaid-js/mermaid/issues/790#issuecomment-568624450), I've updated mermaid to `8.4.4` and added default font.

I'm going to release next version (`2.0.0`) of mermaid.ink

**Comment by jihchi** [comment]
mermaind.ink 2.0.0 has been deployed. it seems better now.

**Comment by WeeJeWel** [comment]
Amazing, thank you!

**Comment by WeeJeWel** [comment]
Amazing, thank you!
