### ISSUE TITLE
`/img` url renders jpeg but is supposed to render png (according to documentation) 

### ISSUE THREAD

**Issue by phibo23** [jihchi/mermaid.ink#110]
I'm wondering if it was originally png and later changed to jpeg for some reason. There are two references to png in the documentation:

1. https://github.com/jihchi/mermaid.ink/blob/53719df8754debb40ee8aae3ffc76ed34b1e75e2/README.md?plain=1#L44
2. In the GitHub Description:
    > Given a mermaid code (markdown-like), serve an image (png or svg) for you 

Furthermore, the [Mermaid Live Editor](https://mermaid.live) editor has a button with a "png" label that links to mermaid.ink (this is actually how I noticed: I followed that link, saved the file and the download dialog stated that I actually downloaded a jpeg file)

If there is in fact a technical reason for choosing jpeg over png, then the documentation should be updated and the maintainers of https://github.com/mermaid-js/mermaid-live-editor should probably be informed, too.

**Comment by jihchi** [comment]
It has been jpeg since beginning:

https://github.com/jihchi/mermaid.ink/blob/ba6269f9f48f026590b698afa8c646bfe7242a5d/src/index.mjs#L42-L46

I believe this is my oversight about mixture/unclar of output format.

IMO, I'd prefer png by default because of transparency.

**Comment by jihchi** [comment]
The [Mermaid Live Editor](https://mermaid.live) has updated the url of the button and now it will generate `png` image.
