### ISSUE TITLE
Can one set the size of the image produced

### ISSUE THREAD

**Issue by jpadfield** [jihchi/mermaid.ink#131]
Hi

Is it was possible to control the size of PNGs created using this? For smaller models it looks great, but for larger ones the resolution can get a bit limited. Perhaps as with a GET variable in the path or something in the config of the model being sent in the first place?

Thanks

**Comment by jihchi** [comment]
A new query parameter in the URL could be a way to go, for example, `?width=100&height=100`.

mermaid.ink won't change the specification of the config because the source of the config comes from [Mermaid Live Editor](https://mermaid.live/).

**Comment by jpadfield** [comment]
If there is not an option already then a consistent default size based on font size might work - basically a given node with a given piece of text will always be rendered at the same size however big the diagram is (subject to the max diagram sizes). 

Consistency is often helpful.

But I can think of lots of use cases where fixing either the width or height  would be good - or perhaps two values to define the maximum bounding box for the diagram? Users might want to be able to distort the width height ratio but I would expect that that would be less common. 

Would this be a lot of work to add in, how is the size done now?
