### ISSUE TITLE
Diagrams with links stopped working

### ISSUE THREAD

**Issue by piranna** [jihchi/mermaid.ink#154]
I have at https://mafalda.io/ several diagrams that make use of the [click](https://mermaid.js.org/syntax/classDiagram.html#interaction) feature to add hyperlinks that worker flawlessly, but since about 1 week ago they stopped rendering. One of the failed diagrams is https://mermaid.ink/svg/eyJjb2RlIjoiZ3JhcGggVERcbm1lZGlhc291cChNZWRpYXNvdXApXG5tZWRpYXNvdXBIb3Jpem9udGFsKE1lZGlhc291cCBIb3Jpem9udGFsKVxucmVtb3RlTWVkaWFzb3VwQ2xpZW50KFJlbW90ZSBNZWRpYXNvdXAgY2xpZW50KVxucmVtb3RlTWVkaWFzb3VwU2VydmVyKFJlbW90ZSBNZWRpYXNvdXAgc2VydmVyKVxuJSUtXG5tYWZhbGRhKE1hZmFsZGEpXG5yZW1vdGVNYWZhbGRhQ2xpZW50KFJlbW90ZSBNYWZhbGRhIGNsaWVudClcbnJlbW90ZU1hZmFsZGFTZXJ2ZXIoUmVtb3RlIE1hZmFsZGEgc2VydmVyKVxuJSUtXG5yZW1vdGVNZWRpYXNvdXBDbGllbnQgLS4tPiByZW1vdGVNZWRpYXNvdXBTZXJ2ZXJcbiUlLVxucmVtb3RlTWVkaWFzb3VwU2VydmVyID09PiBtZWRpYXNvdXBcbnJlbW90ZU1lZGlhc291cFNlcnZlciA9PT4gbWVkaWFzb3VwSG9yaXpvbnRhbFxucmVtb3RlTWVkaWFzb3VwU2VydmVyIC0tPiByZW1vdGVNZWRpYXNvdXBDbGllbnRcbiUlLVxubWVkaWFzb3VwSG9yaXpvbnRhbCA9PT4gbWVkaWFzb3VwXG5tZWRpYXNvdXBIb3Jpem9udGFsIC0tPiBtZWRpYXNvdXBIb3Jpem9udGFsXG5tZWRpYXNvdXBIb3Jpem9udGFsID09PiByZW1vdGVNZWRpYXNvdXBDbGllbnRcbiUlLVxubWFmYWxkYSA9PT4gbWVkaWFzb3VwXG5tYWZhbGRhID09PiBtZWRpYXNvdXBIb3Jpem9udGFsXG5tYWZhbGRhID09PiByZW1vdGVNZWRpYXNvdXBDbGllbnRcbiUlLVxucmVtb3RlTWFmYWxkYUNsaWVudCAtLi0-IHJlbW90ZU1hZmFsZGFTZXJ2ZXJcbiUlLVxucmVtb3RlTWFmYWxkYVNlcnZlciA9PT4gbWVkaWFzb3VwSG9yaXpvbnRhbFxucmVtb3RlTWFmYWxkYVNlcnZlciA9PT4gcmVtb3RlTWVkaWFzb3VwQ2xpZW50XG4lJSByZW1vdGVNYWZhbGRhU2VydmVyID09PiByZW1vdGVNZWRpYXNvdXBTZXJ2ZXJcbnJlbW90ZU1hZmFsZGFTZXJ2ZXIgPT0-IG1lZGlhc291cFxuJSUtXG5jbGFzc0RlZiBtYWZhbGRhQXBpICAgICAgICAgZmlsbDojRUQ4NzJELHN0cm9rZTojMzMzXG5jbGFzc0RlZiBtZWRpYXNvdXBBUEkgICAgICAgZmlsbDojMWViNmU4LHN0cm9rZTojMzMzLGZvbnQtZmFtaWx5OlBvaXJldE9uZVxuY2xhc3NEZWYgcmVtb3RlTWVkaWFzb3VwQVBJIGZpbGw6IzlmNixzdHJva2U6IzMzM1xuJSUtXG5jbGFzcyBtZWRpYXNvdXAsbWVkaWFzb3VwSG9yaXpvbnRhbCxyZW1vdGVNZWRpYXNvdXBDbGllbnQgbWVkaWFzb3VwQVBJXG5jbGFzcyBtYWZhbGRhLHJlbW90ZU1hZmFsZGFDbGllbnQgbWFmYWxkYUFwaVxuY2xhc3MgcmVtb3RlTWFmYWxkYVNlcnZlcixyZW1vdGVNZWRpYXNvdXBTZXJ2ZXIgcmVtb3RlTWVkaWFzb3VwQVBJXG4lJS1cbmNsaWNrIG1lZGlhc291cCBcImh0dHBzOi8vbWVkaWFzb3VwLm9yZy9cIlxuY2xpY2sgbWVkaWFzb3VwSG9yaXpvbnRhbCBcIk1lZGlhc291cC1ob3Jpem9udGFsXCJcbmNsaWNrIHJlbW90ZU1lZGlhc291cENsaWVudCBcIlJlbW90ZS1NZWRpYXNvdXAtY2xpZW50XCJcbmNsaWNrIHJlbW90ZU1lZGlhc291cFNlcnZlciBcIlJlbW90ZS1NZWRpYXNvdXAtc2VydmVyXCJcbmNsaWNrIG1hZmFsZGEgXCJNYWZhbGRhXCJcbmNsaWNrIHJlbW90ZU1hZmFsZGFDbGllbnQgXCJSZW1vdGUtTWFmYWxkYS1jbGllbnRcIlxuY2xpY2sgcmVtb3RlTWFmYWxkYVNlcnZlciBcIlJlbW90ZS1NYWZhbGRhLXNlcnZlclwiIiwibWVybWFpZCI6bnVsbH0, and when displaying it directly in the browser instead of embedded as an image, I get the next error:

```
This page contains the following errors:
error on line 1 at column 17149: Namespace prefix xlink for href on a is not defined
Below is a rendering of the page up to the first error.
```

I've reviewed the base64 string and it only have the mermaid code, so the problem needs to be in the mermaid.ink rendering code.

**Comment by piranna** [comment]
I created the images with https://github.com/jeffreytse/jekyll-spaceship, I have changed its config to `pre-fetch` so they are generated at build time and embeded, and it has worked properly, so not in a hurry (and a better option), just only the issue that online rendering stopped working at of a sudden needs to be reviewed anyway.

**Comment by jihchi** [comment]
Latest deployment was about 2 weeks, let me check if there something is broken.

Thanks for the report.

**Comment by piranna** [comment]
You are welcome :-)

**Comment by jihchi** [comment]
Hi @piranna,

I've addressed the issue and it should be working now. Please reopen the issue if it doesn't work for you.

**Comment by piranna** [comment]
Thank you :-)
