### ISSUE TITLE
could no longer open links 

### ISSUE THREAD

**Issue by mpoggicalinda** [jihchi/mermaid.ink#16]
Hello , 

i got a serie of 4 diagrams , created on last October , that i can no longer open , 
I have the following message : 
" Error 1036 Ray ID: 61709082096d081c • 2021-01-25 08:18:36 UTC
Invalid request rewrite
What happened?
You've requested a page on a website (mermaid.ink) that tried to apply a rewrite rule, but that rewrite is not valid.
What can I do?
It is possible that your request contains an unexpectedly long value."

Is there any way I could recover those original diagrams ?

**Comment by jihchi** [comment]
Unfortunately, the load balancer (Cloudflare) in front of mermaid.ink has imposed a limitation of maximum URL, please see Cloudflare's support response [here](https://github.com/jihchi/mermaid.ink/issues/15#issuecomment-765129855).

You could still open those diagrams in [mermaid-live-editor](https://mermaid-js.github.io/mermaid-live-editor/).

**Comment by jihchi** [comment]
Same as #15 and #11

**Comment by mpoggicalinda** [comment]
thanks for your reply

**Comment by jihchi** [comment]
After #32 is resolved, this issue could be resolved as well.
