### ISSUE TITLE
Text does not fit in nodes

### ISSUE THREAD

**Issue by fkohrt** [jihchi/mermaid.ink#18]
Sometimes nodes are too small to fit the text inside them. Strangely, this is only an issue for `mermaid.ink`, but not for "Download SVG" at the Mermaid Live Editor.

Take, for example, the following code:

```mermaid
graph TD
    A("I don't know what to write here (brackets)")
    B("I need some more inspiration")
    C("What is it that I could write here?")
    D("This is the last piece of content")

    A --- B
    B --- C
    A --- D

```

The last text part of each node is cut off:

![mermaid](https://user-images.githubusercontent.com/12914806/111909621-560a3300-8a5e-11eb-817d-68ddae19e34c.png)

Links with this example:

- [Mermaid Live Editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBKFwiSSBkb24ndCBrbm93IHdoYXQgdG8gd3JpdGUgaGVyZSAoYnJhY2tldHMpXCIpXG4gICAgQihcIkkgbmVlZCBzb21lIG1vcmUgaW5zcGlyYXRpb25cIilcbiAgICBDKFwiV2hhdCBpcyBpdCB0aGF0IEkgY291bGQgd3JpdGUgaGVyZT9cIilcbiAgICBEKFwiVGhpcyBpcyB0aGUgbGFzdCBwaWVjZSBvZiBjb250ZW50XCIpXG5cbiAgICBBIC0tLSBCXG4gICAgQiAtLS0gQ1xuICAgIEEgLS0tIERcbiIsIm1lcm1haWQiOnt9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)
- [`mermaid.ink`](https://mermaid.ink/svg/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBKFwiSSBkb24ndCBrbm93IHdoYXQgdG8gd3JpdGUgaGVyZSAoYnJhY2tldHMpXCIpXG4gICAgQihcIkkgbmVlZCBzb21lIG1vcmUgaW5zcGlyYXRpb25cIilcbiAgICBDKFwiV2hhdCBpcyBpdCB0aGF0IEkgY291bGQgd3JpdGUgaGVyZT9cIilcbiAgICBEKFwiVGhpcyBpcyB0aGUgbGFzdCBwaWVjZSBvZiBjb250ZW50XCIpXG5cbiAgICBBIC0tLSBCXG4gICAgQiAtLS0gQ1xuICAgIEEgLS0tIERcbiIsIm1lcm1haWQiOnt9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

**Comment by jihchi** [comment]
Hi @fkohrt , Thanks for reporting!

I have taken a look and it seems to be an issue on mermaid.js side, see similar issues:
* https://github.com/mermaid-js/mermaid/issues/1485
* https://github.com/mermaid-js/mermaid/issues/1540

There is a work-around by setting an extra CSS, please see [here](https://github.com/mermaid-js/mermaid/issues/790#issuecomment-478860052). 

It will looks like this:
![scale font-size by 90%](https://mermaid.ink/svg/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBKFwiSSBkb24ndCBrbm93IHdoYXQgdG8gd3JpdGUgaGVyZSAoYnJhY2tldHMpXCIpXG4gICAgQihcIkkgbmVlZCBzb21lIG1vcmUgaW5zcGlyYXRpb25cIilcbiAgICBDKFwiV2hhdCBpcyBpdCB0aGF0IEkgY291bGQgd3JpdGUgaGVyZT9cIilcbiAgICBEKFwiVGhpcyBpcyB0aGUgbGFzdCBwaWVjZSBvZiBjb250ZW50XCIpXG5cbiAgICBBIC0tLSBCXG4gICAgQiAtLS0gQ1xuICAgIEEgLS0tIERcbiIsIm1lcm1haWQiOnsidGhlbWVDU1MiOiIubGFiZWwgZm9yZWlnbk9iamVjdCB7IGZvbnQtc2l6ZTogOTAlIH0ifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

* [Mermaid Live Editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBKFwiSSBkb24ndCBrbm93IHdoYXQgdG8gd3JpdGUgaGVyZSAoYnJhY2tldHMpXCIpXG4gICAgQihcIkkgbmVlZCBzb21lIG1vcmUgaW5zcGlyYXRpb25cIilcbiAgICBDKFwiV2hhdCBpcyBpdCB0aGF0IEkgY291bGQgd3JpdGUgaGVyZT9cIilcbiAgICBEKFwiVGhpcyBpcyB0aGUgbGFzdCBwaWVjZSBvZiBjb250ZW50XCIpXG5cbiAgICBBIC0tLSBCXG4gICAgQiAtLS0gQ1xuICAgIEEgLS0tIERcbiIsIm1lcm1haWQiOnsidGhlbWVDU1MiOiIubGFiZWwgZm9yZWlnbk9iamVjdCB7IGZvbnQtc2l6ZTogOTAlIH0ifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)
* [mermaid.ink](https://mermaid.ink/svg/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBKFwiSSBkb24ndCBrbm93IHdoYXQgdG8gd3JpdGUgaGVyZSAoYnJhY2tldHMpXCIpXG4gICAgQihcIkkgbmVlZCBzb21lIG1vcmUgaW5zcGlyYXRpb25cIilcbiAgICBDKFwiV2hhdCBpcyBpdCB0aGF0IEkgY291bGQgd3JpdGUgaGVyZT9cIilcbiAgICBEKFwiVGhpcyBpcyB0aGUgbGFzdCBwaWVjZSBvZiBjb250ZW50XCIpXG5cbiAgICBBIC0tLSBCXG4gICAgQiAtLS0gQ1xuICAgIEEgLS0tIERcbiIsIm1lcm1haWQiOnsidGhlbWVDU1MiOiIubGFiZWwgZm9yZWlnbk9iamVjdCB7IGZvbnQtc2l6ZTogOTAlIH0ifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

**Comment by fkohrt** [comment]
Hi @jihchi, thanks for following up and the quick fix! Closing this as it's an issue with upstream.
