### ISSUE TITLE
Specify a Mermaid theme in URL?

### ISSUE THREAD

**Issue by hrumhurum** [jihchi/mermaid.ink#231]
The diagrams are rendered well on white backgrounds, but on dark backgrounds they become hardly visible. A good solution for that would be to specify a Mermaid theme using a URL parameter, like so: `...?theme=dark`.

The existing `bgColor` parameter does not fully cut it because resulting diagrams look ugly on dark backgrounds.

**Comment by jihchi** [comment]
Hi, does [the diagram-specific theme](https://mermaid.js.org/config/theming.html#diagram-specific-themes) work for you?

For example, you could add `%%{init: {'theme':'dark'}}%%` to the [mermaid code](https://mermaid.live/edit#pako:eNo9Tr0OwiAQfpXLJYSlfQEGpzo66chylqslFtrgMRjCu0trdPv-8xUcV8doUKnioxcDRcvMgbXRjtJT16qUjQCPRNsMt2HHAAR9f4I7dhg4BfKuLZTdsni0LZoGHU-UF7FoY21RyrJe33FEIylzh3lzJDx4atsBzUTL66-enZc1_ZJ8sMv36XG4fgA-ZDyl):

```
%%{init: {'theme':'dark'}}%%
  graph TD
    a --> b
```

<details> 
<summary>rendered image (svg) (click to expand)</summary>

![mermaid.ink](https://mermaid.ink/svg/pako:eNo9Tr0OwiAQfpXLJYSlfQEGpzo66chylqslFtrgMRjCu0trdPv-8xUcV8doUKnioxcDRcvMgbXRjtJT16qUjQCPRNsMt2HHAAR9f4I7dhg4BfKuLZTdsni0LZoGHU-UF7FoY21RyrJe33FEIylzh3lzJDx4atsBzUTL66-enZc1_ZJ8sMv36XG4fgA-ZDyl)
</details>

Anyway, passing `?theme=...` as a [side-wide theme](https://mermaid.js.org/config/theming.html#site-wide-theme) sounds a good idea 👍

**Comment by hrumhurum** [comment]
>Hi, does [the diagram-specific theme](https://mermaid.js.org/config/theming.html#diagram-specific-themes) work for you?

It works. And it allowed me to work around the problem. `?theme=...` would be more convenient though to avoid having different `pako:` in URLs for the same content.
