### ISSUE TITLE
Mermaid Ink silently accepts a subset of Fontawesome icons so fa-car works but not fa-broadcast-tower

### ISSUE THREAD

**Issue by jihchi** [jihchi/mermaid.ink#25]
The original issue is from https://github.com/mermaid-js/mermaid-live-editor/issues/180 by @richtong

> **Describe the bug**
> ONly some Font Awesome icons seem to work so is there a list of what you accept or is there a way that you can include the CSS include so that all fonts can be rendered. Thanks!
> 
> **To Reproduce**
> Link to Live Editor:
> Steps to reproduce the behavior:
> 
> 1. Enter the chart
> 
> C(fa:fa-car Car) --- B(fa:fa-broadcast-tower)
> 
> **Expected behavior**
> It should render both the car and a broadcast tower (a free icon available now)
> 
> **Screenshots**
> 
> **Desktop (please complete the following information):**
> 
> * OS: Mac
> * Browser Safari
> * Version v11
> 
> **Additional context**
> Add any other context about the problem here.

**Comment by mmorel-35** [comment]
It's seems like fa-broadcast-tower is  a font-awesome 5 icon.
A migration from "font-awesome" to "@fortawesome/font-awesome-free" is going to be necessary to be able to handle this new icon

**Comment by jihchi** [comment]
Hi @mmorel-35 , 

I've upgraded font-awesome to v5 and deployed to marmaid.ink, it should work now.

Thank you!
