### ISSUE TITLE
Cannot make latex support work

### ISSUE THREAD

**Issue by juangburgos** [jihchi/mermaid.ink#327]
When I put the following in the [Mermaid Live Editor](https://mermaid.live/), it works:

```
graph LR;
    A["$$x = \alpha$$"]--> B & C & D;
    B--> A & E;
    C--> A & E;
    D--> A & E;
    E--> B & C & D;
```

This is the output:

![image](https://github.com/jihchi/mermaid.ink/assets/4707341/5c5e2c6e-40e9-405a-8b73-7b0ad5995d30)

But when I paste the encoded string after `https://mermaid.ink/img/ *` it does not work:

![image](https://github.com/jihchi/mermaid.ink/assets/4707341/923eac51-476c-496a-b4c5-ea0981b42284)

This is the URL:

<https://mermaid.ink/img/pako:eNpdj8sKg0AMRX8lhKEr_YEpLfjaddUumy6CE6vgqNgZaBH_vRFcGQiEw-Fys2A9OkGL75mnFm73Mw2gkz0JjfnCBYi4n1o2hvCVplfI4QSFbrmb-QYzBdUOiiMoj6A65mCCXmbPndMmyyYRhla8EFo9nTQc-0BIw6oqxzA-fkONNsxREoyT4yBlx_qDR9tw_5H1D0SiOyA>

Might be doing somethins wrong? Appreciate any help.

**Comment by jihchi** [comment]
Hi @juangburgos, thanks for the report.

Mermaid's latex support was introduced in [v10.9.0](https://github.com/mermaid-js/mermaid/releases/tag/v10.9.0) and the service is using `v10.8.0`.

I'll upgrade the version soon.

**Comment by juangburgos** [comment]
Makes sense, thank you for the reply and for the great work!

**Comment by jihchi** [comment]
I've upgraded the version and it should work now.

Please let me know if it does not work for you.
