### ISSUE TITLE
Rendering width too small

### ISSUE THREAD

**Issue by thgossler** [jihchi/mermaid.ink#374]
It seems there is not way to get the following Mermaid diagram rendered nicely on mermaid.ink with the current implementation. 

[Diagram on Mermaid.live](https://mermaid.live/edit#pako:eNqdVm1v4jgQ_isj337gpNCS8lJAug8trXRdLXtc093tnpAq4xiwGuzIdqBc1f9-YwdCkoXu3fGF5LFn5pnH45m8EqZiToYE8DfqjJS0VEiup9IBVtiEQwFCLOhC0xXMlYY7abmW3MI1lc9CLiDaGstXU5mb5m9Pty-2wVdUJE_GAwFMyW1zjMB-P3HQw5KD8A5pAmPBtDJqbuH2hS2pXHAwxd4Pli7Mb1OyDs9aU_JrHmzCtVGywTJj1YrrAEbF05RcwR4HNQeLkWbIOICNsEtIvSUGdRhQxlQmrTkaKA9ViPF0jVtjqrcNFrowdT3QBl5zm4pdw6TU7Y9wT8KbE4rpXaVprsNHuqYR0yK1AVzJRZZQnS9MtFqLmBugSeJzKMLNdvLPM8mscLkIuwWrMGuftIG1oM5EaNjwGcy02hg84L121aTcea3UTCT8iaapizz2bweKo18CeKQrqoWsU4NErITlMZhsZpDaTu5_Q9X8wDVnATFfC8aPs21gPnua3zA15JgIRp3rg5wBRKl2UcdfRzl6wxOxdsEcOWNxPwOGPrm0QGV8nHM0uTpO4mbWiKmlM2q4d757zkNFf36CGmKVRq0yPALQfCGM1Z4wlj_eqpV_DmBJzRJ1pBmWKNM8RmqCJiZwFcqNgUQt8IVbdnaKlD_JGWXPXMaokfA3YXJ3SqMbhTv1wUHtaH9yhO7U0Hnpmrwd6QM721InwD4g59hQeL2JlKVyFb-rJIZAQaEkGNCZyuyhjILiJgeA-kpDPdmyZDm7e56UukapnL4YbnIWvz88TKJC5S8pHjZHs8huE37M9oOaz7H4v2Pr6LV8I8mBRwQGh5ZVjbzrCf85qrcrRWx2TkWoXuo80M-8l23KQdqtmoRF8rs89jfsVIjq_pJAYbvK36_XqvggEjVbyQL4GP3x-bwqmLMts_9_Lp6u0ax0u2te7jmNDcy1Wvm2sdHY-7CpqNzzzvHN9agmVnUcstKkitC5Ad50G3JHx-U75aEkZLPTrYhRoV4fyNW4mfHT65BDNH6YnKLyjt9yxfRap9n82BYOx-MInO_O6HH86fzda_Gu1zKbbv1eNsPOvqRJQFBLTCTGjyI_v6cEW88K2_cQH3HgP6NxjrOOA3dDfkqwp38TsV060OqMB_uFzR7ttloFiENusbQOvSih6GNMX467YZ1oSVN-J-_Vxi22Syv7j5FiMTxE1zR1yBwHCHcg9uY3nyiOFxWhtmTo45DM63mTf-TtwZTKv5Qqv5LhK3khw2bYap_1w26_1w0Hg36v3-8HZEuGYe_yLGy324NBq98OLy67bwH523sIz9oX3fYgvOwNOi38G1wGhMcC2_w4_wj136Jv_wAK-HmS)

[Same diagram on Mermaid.ink](https://mermaid.ink/img/pako:eNqdVm1v4jgQ_isj337gpNCS8lJAug8trXRdLXtc093tnpAq4xiwGuzIdqBc1f9-YwdCkoXu3fGF5LFn5pnH45m8EqZiToYE8DfqjJS0VEiup9IBVtiEQwFCLOhC0xXMlYY7abmW3MI1lc9CLiDaGstXU5mb5m9Pty-2wVdUJE_GAwFMyW1zjMB-P3HQw5KD8A5pAmPBtDJqbuH2hS2pXHAwxd4Pli7Mb1OyDs9aU_JrHmzCtVGywTJj1YrrAEbF05RcwR4HNQeLkWbIOICNsEtIvSUGdRhQxlQmrTkaKA9ViPF0jVtjqrcNFrowdT3QBl5zm4pdw6TU7Y9wT8KbE4rpXaVprsNHuqYR0yK1AVzJRZZQnS9MtFqLmBugSeJzKMLNdvLPM8mscLkIuwWrMGuftIG1oM5EaNjwGcy02hg84L121aTcea3UTCT8iaapizz2bweKo18CeKQrqoWsU4NErITlMZhsZpDaTu5_Q9X8wDVnATFfC8aPs21gPnua3zA15JgIRp3rg5wBRKl2UcdfRzl6wxOxdsEcOWNxPwOGPrm0QGV8nHM0uTpO4mbWiKmlM2q4d757zkNFf36CGmKVRq0yPALQfCGM1Z4wlj_eqpV_DmBJzRJ1pBmWKNM8RmqCJiZwFcqNgUQt8IVbdnaKlD_JGWXPXMaokfA3YXJ3SqMbhTv1wUHtaH9yhO7U0Hnpmrwd6QM721InwD4g59hQeL2JlKVyFb-rJIZAQaEkGNCZyuyhjILiJgeA-kpDPdmyZDm7e56UukapnL4YbnIWvz88TKJC5S8pHjZHs8huE37M9oOaz7H4v2Pr6LV8I8mBRwQGh5ZVjbzrCf85qrcrRWx2TkWoXuo80M-8l23KQdqtmoRF8rs89jfsVIjq_pJAYbvK36_XqvggEjVbyQL4GP3x-bwqmLMts_9_Lp6u0ax0u2te7jmNDcy1Wvm2sdHY-7CpqNzzzvHN9agmVnUcstKkitC5Ad50G3JHx-U75aEkZLPTrYhRoV4fyNW4mfHT65BDNH6YnKLyjt9yxfRap9n82BYOx-MInO_O6HH86fzda_Gu1zKbbv1eNsPOvqRJQFBLTCTGjyI_v6cEW88K2_cQH3HgP6NxjrOOA3dDfkqwp38TsV060OqMB_uFzR7ttloFiENusbQOvSih6GNMX467YZ1oSVN-J-_Vxi22Syv7j5FiMTxE1zR1yBwHCHcg9uY3nyiOFxWhtmTo45DM63mTf-TtwZTKv5Qqv5LhK3khw2bYap_1w26_1w0Hg36v3-8HZEuGYe_yLGy324NBq98OLy67bwH523sIz9oX3fYgvOwNOi38G1wGhMcC2_w4_wj136Jv_wAK-HmS?type=png)

I could not figure out what needs to be changed in the code to ensure that the rendering on mermaid.ink looks the same as in mermaid.live.

I don't think that the Chrome command line arguments are relevant. I rather believe that there is something wrong with the width/height settings in the HTML. Maybe a combination of both.

I have tried `'--window-size=1920,1080'` without success. I played with `max-width` and `height` CSS properties on various elements, but couldn't find out what does the trick. It would be highly welcome if somebody deeply understanding the code could suggest a solution or workaround.

**Comment by jihchi** [comment]
Hi @thgossler, may I know what width were you looking for?

The [svg format](https://mermaid.ink/svg/pako:eNqdVm1v4jgQ_isj337gpNCS8lJAug8trXRdLXtc093tnpAq4xiwGuzIdqBc1f9-YwdCkoXu3fGF5LFn5pnH45m8EqZiToYE8DfqjJS0VEiup9IBVtiEQwFCLOhC0xXMlYY7abmW3MI1lc9CLiDaGstXU5mb5m9Pty-2wVdUJE_GAwFMyW1zjMB-P3HQw5KD8A5pAmPBtDJqbuH2hS2pXHAwxd4Pli7Mb1OyDs9aU_JrHmzCtVGywTJj1YrrAEbF05RcwR4HNQeLkWbIOICNsEtIvSUGdRhQxlQmrTkaKA9ViPF0jVtjqrcNFrowdT3QBl5zm4pdw6TU7Y9wT8KbE4rpXaVprsNHuqYR0yK1AVzJRZZQnS9MtFqLmBugSeJzKMLNdvLPM8mscLkIuwWrMGuftIG1oM5EaNjwGcy02hg84L121aTcea3UTCT8iaapizz2bweKo18CeKQrqoWsU4NErITlMZhsZpDaTu5_Q9X8wDVnATFfC8aPs21gPnua3zA15JgIRp3rg5wBRKl2UcdfRzl6wxOxdsEcOWNxPwOGPrm0QGV8nHM0uTpO4mbWiKmlM2q4d757zkNFf36CGmKVRq0yPALQfCGM1Z4wlj_eqpV_DmBJzRJ1pBmWKNM8RmqCJiZwFcqNgUQt8IVbdnaKlD_JGWXPXMaokfA3YXJ3SqMbhTv1wUHtaH9yhO7U0Hnpmrwd6QM721InwD4g59hQeL2JlKVyFb-rJIZAQaEkGNCZyuyhjILiJgeA-kpDPdmyZDm7e56UukapnL4YbnIWvz88TKJC5S8pHjZHs8huE37M9oOaz7H4v2Pr6LV8I8mBRwQGh5ZVjbzrCf85qrcrRWx2TkWoXuo80M-8l23KQdqtmoRF8rs89jfsVIjq_pJAYbvK36_XqvggEjVbyQL4GP3x-bwqmLMts_9_Lp6u0ax0u2te7jmNDcy1Wvm2sdHY-7CpqNzzzvHN9agmVnUcstKkitC5Ad50G3JHx-U75aEkZLPTrYhRoV4fyNW4mfHT65BDNH6YnKLyjt9yxfRap9n82BYOx-MInO_O6HH86fzda_Gu1zKbbv1eNsPOvqRJQFBLTCTGjyI_v6cEW88K2_cQH3HgP6NxjrOOA3dDfkqwp38TsV060OqMB_uFzR7ttloFiENusbQOvSih6GNMX467YZ1oSVN-J-_Vxi22Syv7j5FiMTxE1zR1yBwHCHcg9uY3nyiOFxWhtmTo45DM63mTf-TtwZTKv5Qqv5LhK3khw2bYap_1w26_1w0Hg36v3-8HZEuGYe_yLGy324NBq98OLy67bwH523sIz9oX3fYgvOwNOi38G1wGhMcC2_w4_wj136Jv_wAK-HmS) is the most similar to Mermaid.live.

**Comment by thgossler** [comment]
I have seen just recently that Mermaid doesn't support the C4 syntax well yet, at least not the layout parts. Hence, this issue is not valid and I will close it.
