### ISSUE TITLE
Collaboration with Mermaid Flow

### ISSUE THREAD

**Issue by ted-marozzi** [jihchi/mermaid.ink#377]
Hello 👋,

Nice work on this project, I run the website [Mermaid Flow](https://www.mermaidflow.app/) and wanted to offer you the chance to become an affiliate of the project. This would mean you earn 40% of all revenue generated for life from users that you refer to Mermaid Flow.

Interested? [DM me on X!](https://x.com/ted_marozzi)

**Comment by jihchi** [comment]
Hi, Thank you for reaching out and for your kind offer, I appreciate the consideration.
