### ISSUE TITLE
404 Not found for some diagrams

### ISSUE THREAD

**Issue by adjerbetian** [jihchi/mermaid.ink#396]
Here is the code of a minimal diagram that I noticed a bug with:

```
flowchart TD
    A --> B["C"]
    Guess["How?"]
```

Here is a python code that can reproduce the error:

```python
import base64

def get_mermaid_url(diagram: str) -> str:
  diagram_encoded = base64.b64encode(diagram.encode('utf8')).decode('ascii')
  return f'https://mermaid.ink/img/{diagram_encoded}'

diagram = '''
flowchart TD
    A --> B["C"]
    Guess["How?"]
'''

print('Working:', get_mermaid_url(diagram))
print('Broken:', get_mermaid_url(diagram.strip()))
```

I get the urls:
- Working: https://mermaid.ink/img/CmZsb3djaGFydCBURAogICAgQSAtLT4gQlsiQyJdCiAgICBHdWVzc1siSG93PyJdCg==
- Broken: https://mermaid.ink/img/Zmxvd2NoYXJ0IFRECiAgICBBIC0tPiBCWyJDIl0KICAgIEd1ZXNzWyJIb3c/Il0=

Stripping the code breaks the link and returns a 404 Not found.

**Comment by adjerbetian** [comment]
I think I understood where the problem comes from: the broken urls has an image's `encodedCode` which includes a `/`, and this breaks the routing mechanism.

**Comment by jihchi** [comment]
Correct. This was the same problem mentioned in mermaid-js/mermaid-live-editor#7.

In Python, please use [urlsafe_b64encode](https://docs.python.org/3/library/base64.html#base64.urlsafe_b64encode) instead. For example:

```diff
--- 
+++ 
@@ -1,14 +1,14 @@
 import base64
 
 def get_mermaid_url(diagram: str) -> str:
-  diagram_encoded = base64.b64encode(diagram.encode('utf8')).decode('ascii')
+  diagram_encoded = base64.urlsafe_b64encode(diagram.encode('utf8')).decode('ascii')
   return f'https://mermaid.ink/img/{diagram_encoded}'
```

**Comment by adjerbetian** [comment]
This worked, thank you very much!! 🙏 🙏 🙏 🙏
