### ISSUE TITLE
Escaping dots breaks in mermaid ink but not in mermaid live

### ISSUE THREAD

**Issue by adjerbetian** [jihchi/mermaid.ink#441]
The following code breaks on mermaid ink:

```
flowchart TD
    Node["1\. Some text"]
```

See [here](https://mermaid.live/edit#pako:eNpFjkFvgzAMhf8K8jlChAwScu6O26U7bdkhIqYgEVKlidoO8d_nUW3zyc9-z_5W6IND0DDM4dqPNqbi7WCWguqVFh8GuDFlcQwei4S3ZOATGHiM3k6OYuuP10Aa0aMBTa3DweaZjGbZyGpzCsf70oNOMSODGPJpBD3Y-UIqn51NeJjsKVr_N0U3pRBfHmA7H4OzXd5D-PeQBr3CDTSveNlWjax53QmpFH9icActlCpbyZuKC9E1kot2Y_C1n6hK1YpaCUWJrpN1I35JnvfPD9btG22ZV10) for the version in mermaid live:

![image](https://github.com/user-attachments/assets/9cd697c4-8f55-4b05-b68b-a15b912c0edc)

and [here](https://mermaid.ink/svg/pako:eNpFjkFvgzAMhf8K8jlChAwScu6O26U7bdkhIqYgEVKlidoO8d_nUW3zyc9-z_5W6IND0DDM4dqPNqbi7WCWguqVFh8GuDFlcQwei4S3ZOATGHiM3k6OYuuP10Aa0aMBTa3DweaZjGbZyGpzCsf70oNOMSODGPJpBD3Y-UIqn51NeJjsKVr_N0U3pRBfHmA7H4OzXd5D-PeQBr3CDTSveNlWjax53QmpFH9icActlCpbyZuKC9E1kot2Y_C1n6hK1YpaCUWJrpN1I35JnvfPD9btG22ZV10) for the version in mermaid ink:

![image](https://github.com/user-attachments/assets/f41dadd5-5fed-41af-a68d-4c7c466016ed)

**Comment by jihchi** [comment]
Hi @adjerbetian. Could you please try again?

I just released a new version [v11.1.0](https://github.com/jihchi/mermaid.ink/releases/tag/v11.1.0) and deployed it to the service. It works for me:

![](https://mermaid.ink/svg/pako:eNpFjkFvgzAMhf8K8jlChAwScu6O26U7bdkhIqYgEVKlidoO8d_nUW3zyc9-z_5W6IND0DDM4dqPNqbi7WCWguqVFh8GuDFlcQwei4S3ZOATGHiM3k6OYuuP10Aa0aMBTa3DweaZjGbZyGpzCsf70oNOMSODGPJpBD3Y-UIqn51NeJjsKVr_N0U3pRBfHmA7H4OzXd5D-PeQBr3CDTSveNlWjax53QmpFH9icActlCpbyZuKC9E1kot2Y_C1n6hK1YpaCUWJrpN1I35JnvfPD9btG22ZV10)

**Comment by adjerbetian** [comment]
Indeed the problem is fixed, thank you!
