### ISSUE TITLE
how to set charset=utf-8 ?

### ISSUE THREAD

**Issue by xjfnet** [jihchi/mermaid.ink#5]
how to set charset=utf-8 ?

**Comment by jihchi** [comment]
I assume you are asking for supporting major charsets?

I just released a version which added support for major charsets:

![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgQVtcIuS7iuaXpeOBr-OAgeS4lueVjFwiXSAtLT58R2V0IG1vbmV5fCBCKFwiwqFIb2xhLCBtdW5kbyFcIilcbiAgQiAtLT4gQ3tcIuS9oOWlve-8jOS4lueVjO-8gVwifVxuICBDIC0tPnxPbmV8IERbTGFwdG9wXVxuICBDIC0tPnxUd298IEVbaVBob25lXVxuICBDIC0tPnxUaHJlZXwgRltmYTpmYS1jYXIgQ2FyXVxuXHRcdCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

**Comment by jihchi** [comment]
I'm going to close this issue at the moment, feel free to re-open it.
