### ISSUE TITLE
Participant background color and box is missing

### ISSUE THREAD

**Issue by gskohner** [jihchi/mermaid.ink#78]
https://mermaid.ink/img/pako:eNpt0M2qAjEMBeBXidk68wJdKILC1a3bbkJ7xin051pbRMR3tzOOO7MK5DuB5MkmWbDiG64V0WDv5JIl6Eitdt4Z9JvN-pTGqOgP3iea-o7GdCfJoEeq25_4w4zEidAIyRSw0GnWN9rPmbbYfdIdHefErFts9ZsfaQA8XTKkLORb3HFADuJsu-k5zTSXEQGaVWstBqm-aNbx1Wj9t1JwsK6kzGoQf0PHUks6P6JhVXLFFy1_WdTrDbKeYug

How do I control the style?

**Comment by jihchi** [comment]
Could you elaborate a bit? Which parts are you referring?

**Comment by gskohner** [comment]
Is the only way to control styling with themevariables?  Here is an example of that approach: 

https://mermaid.ink/img/pako:eNpt0EtqxDAMBuCrqILgRZMLeDGlpYWZbgtdeaOJlcTUj9axKUPw3es8uhuvhPX9AmnBPmhGiU2zGG-ShEWkiR0LCULzQNkm0cL-90nR0NXyXJsLCEfGv3yNq7zazKKU0jTKKz_zT2bf86uhMZJTHup7tqbn7nR6fA-Tl3BmawOsdQtT-AWKDLeQn-7infXkVwITUwTHB117XaXdlqmDzZ5u4bIlNl1jD_f5BQZmC2NkSpVgi45j3UzXmyxrROG2u0JZy-MiCpUvleZvTYnftEkhohzIztwi5RQ-br5HmWLmf3Tc4lDlD02Heos

**Comment by jihchi** [comment]
You can change background color by adding extra query parameter (e.g. `?bgColor=FF000`) to the URLs:

https://mermaid.ink/img/pako:eNpt0EtqxDAMBuCrqILgRZMLeDGlpYWZbgtdeaOJlcTUj9axKUPw3es8uhuvhPX9AmnBPmhGiU2zGG-ShEWkiR0LCULzQNkm0cL-90nR0NXyXJsLCEfGv3yNq7zazKKU0jTKKz_zT2bf86uhMZJTHup7tqbn7nR6fA-Tl3BmawOsdQtT-AWKDLeQn-7infXkVwITUwTHB117XaXdlqmDzZ5u4bIlNl1jD_f5BQZmC2NkSpVgi45j3UzXmyxrROG2u0JZy-MiCpUvleZvTYnftEkhohzIztwi5RQ-br5HmWLmf3Tc4lDlD02Heos?bgColor=!yellow <-- note the `?bgColor` here

For more details, see https://mermaid.ink/.
